server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 2

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: carModule
        uri: lb://CAR-SERVICE
        predicates:
          - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/view/**,/api/cars/**